server:
  port: 8084

spring:
  application:
    name: fs-client
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info

# application.yml
grpc:
  client:
    tunnel-service:
      address: static://localhost:9090
      negotiation-type: plaintext
      tunnel:
        enabled: true
    tunnel-service1:
      address: static://localhost:9090
      negotiation-type: plaintext
      tunnel:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG
