// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tunnel.proto

// Protobuf Java Version: 3.25.3
package top.redjujubetree.grpc.tunnel.proto;

public final class GrpcTunnelProto {
  private GrpcTunnelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_redjujubetree_tunnel_grpc_RequestPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_redjujubetree_tunnel_grpc_RequestPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_redjujubetree_tunnel_grpc_ResponsePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_redjujubetree_tunnel_grpc_ResponsePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014tunnel.proto\022\035top.redjujubetree.tunnel" +
      ".grpc\"\235\002\n\rTunnelMessage\022\022\n\nmessage_id\030\001 " +
      "\001(\t\022\021\n\tclient_id\030\002 \001(\t\0228\n\004type\030\003 \001(\0162*.t" +
      "op.redjujubetree.tunnel.grpc.MessageType" +
      "\022\021\n\ttimestamp\030\004 \001(\003\022>\n\007request\030\005 \001(\0132-.t" +
      "op.redjujubetree.tunnel.grpc.RequestPayl" +
      "oad\022@\n\010response\030\006 \001(\0132..top.redjujubetre" +
      "e.tunnel.grpc.ResponsePayload\022\026\n\016correla" +
      "tion_id\030\007 \001(\t\",\n\016RequestPayload\022\014\n\004type\030" +
      "\001 \001(\t\022\014\n\004data\030\002 \001(\014\"L\n\017ResponsePayload\022\014" +
      "\n\004type\030\001 \001(\t\022\014\n\004code\030\002 \001(\005\022\017\n\007message\030\003 " +
      "\001(\t\022\014\n\004data\030\004 \001(\014*_\n\013MessageType\022\022\n\016SERV" +
      "ER_REQUEST\020\000\022\023\n\017SERVER_RESPONSE\020\001\022\022\n\016CLI" +
      "ENT_REQUEST\020\002\022\023\n\017CLIENT_RESPONSE\020\0032\206\001\n\021G" +
      "rpcTunnelService\022q\n\017EstablishTunnel\022,.to" +
      "p.redjujubetree.tunnel.grpc.TunnelMessag" +
      "e\032,.top.redjujubetree.tunnel.grpc.Tunnel" +
      "Message(\0010\001B8\n#top.redjujubetree.grpc.tu" +
      "nnel.protoB\017GrpcTunnelProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_descriptor,
        new java.lang.String[] { "MessageId", "ClientId", "Type", "Timestamp", "Request", "Response", "CorrelationId", });
    internal_static_top_redjujubetree_tunnel_grpc_RequestPayload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_top_redjujubetree_tunnel_grpc_RequestPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_redjujubetree_tunnel_grpc_RequestPayload_descriptor,
        new java.lang.String[] { "Type", "Data", });
    internal_static_top_redjujubetree_tunnel_grpc_ResponsePayload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_top_redjujubetree_tunnel_grpc_ResponsePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_redjujubetree_tunnel_grpc_ResponsePayload_descriptor,
        new java.lang.String[] { "Type", "Code", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
