// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tunnel.proto

// Protobuf Java Version: 3.25.3
package top.redjujubetree.grpc.tunnel.proto;

/**
 * <pre>
 * message types for the tunnel
 * </pre>
 *
 * Protobuf enum {@code top.redjujubetree.tunnel.grpc.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SERVER_REQUEST = 0;</code>
   */
  SERVER_REQUEST(0),
  /**
   * <code>SERVER_RESPONSE = 1;</code>
   */
  SERVER_RESPONSE(1),
  /**
   * <code>CLIENT_REQUEST = 2;</code>
   */
  CLIENT_REQUEST(2),
  /**
   * <code>CLIENT_RESPONSE = 3;</code>
   */
  CLIENT_RESPONSE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SERVER_REQUEST = 0;</code>
   */
  public static final int SERVER_REQUEST_VALUE = 0;
  /**
   * <code>SERVER_RESPONSE = 1;</code>
   */
  public static final int SERVER_RESPONSE_VALUE = 1;
  /**
   * <code>CLIENT_REQUEST = 2;</code>
   */
  public static final int CLIENT_REQUEST_VALUE = 2;
  /**
   * <code>CLIENT_RESPONSE = 3;</code>
   */
  public static final int CLIENT_RESPONSE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return SERVER_REQUEST;
      case 1: return SERVER_RESPONSE;
      case 2: return CLIENT_REQUEST;
      case 3: return CLIENT_RESPONSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return top.redjujubetree.grpc.tunnel.proto.GrpcTunnelProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:top.redjujubetree.tunnel.grpc.MessageType)
}

