// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tunnel.proto

// Protobuf Java Version: 3.25.3
package top.redjujubetree.grpc.tunnel.proto;

public interface RequestPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.redjujubetree.tunnel.grpc.RequestPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
