// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tunnel.proto

// Protobuf Java Version: 3.25.3
package top.redjujubetree.grpc.tunnel.proto;

/**
 * <pre>
 * common message structure
 * </pre>
 *
 * Protobuf type {@code top.redjujubetree.tunnel.grpc.TunnelMessage}
 */
public final class TunnelMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:top.redjujubetree.tunnel.grpc.TunnelMessage)
    TunnelMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TunnelMessage.newBuilder() to construct.
  private TunnelMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TunnelMessage() {
    messageId_ = "";
    clientId_ = "";
    type_ = 0;
    correlationId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TunnelMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return top.redjujubetree.grpc.tunnel.proto.GrpcTunnelProto.internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return top.redjujubetree.grpc.tunnel.proto.GrpcTunnelProto.internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            top.redjujubetree.grpc.tunnel.proto.TunnelMessage.class, top.redjujubetree.grpc.tunnel.proto.TunnelMessage.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <pre>
   * 消息ID
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息ID
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientId_ = "";
  /**
   * <pre>
   * 客户端ID
   * </pre>
   *
   * <code>string client_id = 2;</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 客户端ID
   * </pre>
   *
   * <code>string client_id = 2;</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_ = 0;
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
   * @return The type.
   */
  @java.lang.Override public top.redjujubetree.grpc.tunnel.proto.MessageType getType() {
    top.redjujubetree.grpc.tunnel.proto.MessageType result = top.redjujubetree.grpc.tunnel.proto.MessageType.forNumber(type_);
    return result == null ? top.redjujubetree.grpc.tunnel.proto.MessageType.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int REQUEST_FIELD_NUMBER = 5;
  private top.redjujubetree.grpc.tunnel.proto.RequestPayload request_;
  /**
   * <pre>
   * 消息载荷
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
   * @return Whether the request field is set.
   */
  @java.lang.Override
  public boolean hasRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 消息载荷
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
   * @return The request.
   */
  @java.lang.Override
  public top.redjujubetree.grpc.tunnel.proto.RequestPayload getRequest() {
    return request_ == null ? top.redjujubetree.grpc.tunnel.proto.RequestPayload.getDefaultInstance() : request_;
  }
  /**
   * <pre>
   * 消息载荷
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
   */
  @java.lang.Override
  public top.redjujubetree.grpc.tunnel.proto.RequestPayloadOrBuilder getRequestOrBuilder() {
    return request_ == null ? top.redjujubetree.grpc.tunnel.proto.RequestPayload.getDefaultInstance() : request_;
  }

  public static final int RESPONSE_FIELD_NUMBER = 6;
  private top.redjujubetree.grpc.tunnel.proto.ResponsePayload response_;
  /**
   * <pre>
   * 响应载荷
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
   * @return Whether the response field is set.
   */
  @java.lang.Override
  public boolean hasResponse() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 响应载荷
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
   * @return The response.
   */
  @java.lang.Override
  public top.redjujubetree.grpc.tunnel.proto.ResponsePayload getResponse() {
    return response_ == null ? top.redjujubetree.grpc.tunnel.proto.ResponsePayload.getDefaultInstance() : response_;
  }
  /**
   * <pre>
   * 响应载荷
   * </pre>
   *
   * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
   */
  @java.lang.Override
  public top.redjujubetree.grpc.tunnel.proto.ResponsePayloadOrBuilder getResponseOrBuilder() {
    return response_ == null ? top.redjujubetree.grpc.tunnel.proto.ResponsePayload.getDefaultInstance() : response_;
  }

  public static final int CORRELATION_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object correlationId_ = "";
  /**
   * <pre>
   * 关联ID，用于请求响应匹配
   * </pre>
   *
   * <code>string correlation_id = 7;</code>
   * @return The correlationId.
   */
  @java.lang.Override
  public java.lang.String getCorrelationId() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      correlationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 关联ID，用于请求响应匹配
   * </pre>
   *
   * <code>string correlation_id = 7;</code>
   * @return The bytes for correlationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCorrelationIdBytes() {
    java.lang.Object ref = correlationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      correlationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
    }
    if (type_ != top.redjujubetree.grpc.tunnel.proto.MessageType.SERVER_REQUEST.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(4, timestamp_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getRequest());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getResponse());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, correlationId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
    }
    if (type_ != top.redjujubetree.grpc.tunnel.proto.MessageType.SERVER_REQUEST.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, timestamp_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getRequest());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getResponse());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, correlationId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof top.redjujubetree.grpc.tunnel.proto.TunnelMessage)) {
      return super.equals(obj);
    }
    top.redjujubetree.grpc.tunnel.proto.TunnelMessage other = (top.redjujubetree.grpc.tunnel.proto.TunnelMessage) obj;

    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (type_ != other.type_) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (hasRequest() != other.hasRequest()) return false;
    if (hasRequest()) {
      if (!getRequest()
          .equals(other.getRequest())) return false;
    }
    if (hasResponse() != other.hasResponse()) return false;
    if (hasResponse()) {
      if (!getResponse()
          .equals(other.getResponse())) return false;
    }
    if (!getCorrelationId()
        .equals(other.getCorrelationId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (hasRequest()) {
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRequest().hashCode();
    }
    if (hasResponse()) {
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
    }
    hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(top.redjujubetree.grpc.tunnel.proto.TunnelMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * common message structure
   * </pre>
   *
   * Protobuf type {@code top.redjujubetree.tunnel.grpc.TunnelMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:top.redjujubetree.tunnel.grpc.TunnelMessage)
      top.redjujubetree.grpc.tunnel.proto.TunnelMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.redjujubetree.grpc.tunnel.proto.GrpcTunnelProto.internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.redjujubetree.grpc.tunnel.proto.GrpcTunnelProto.internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.redjujubetree.grpc.tunnel.proto.TunnelMessage.class, top.redjujubetree.grpc.tunnel.proto.TunnelMessage.Builder.class);
    }

    // Construct using top.redjujubetree.grpc.tunnel.proto.TunnelMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRequestFieldBuilder();
        getResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageId_ = "";
      clientId_ = "";
      type_ = 0;
      timestamp_ = 0L;
      request_ = null;
      if (requestBuilder_ != null) {
        requestBuilder_.dispose();
        requestBuilder_ = null;
      }
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      correlationId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return top.redjujubetree.grpc.tunnel.proto.GrpcTunnelProto.internal_static_top_redjujubetree_tunnel_grpc_TunnelMessage_descriptor;
    }

    @java.lang.Override
    public top.redjujubetree.grpc.tunnel.proto.TunnelMessage getDefaultInstanceForType() {
      return top.redjujubetree.grpc.tunnel.proto.TunnelMessage.getDefaultInstance();
    }

    @java.lang.Override
    public top.redjujubetree.grpc.tunnel.proto.TunnelMessage build() {
      top.redjujubetree.grpc.tunnel.proto.TunnelMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public top.redjujubetree.grpc.tunnel.proto.TunnelMessage buildPartial() {
      top.redjujubetree.grpc.tunnel.proto.TunnelMessage result = new top.redjujubetree.grpc.tunnel.proto.TunnelMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(top.redjujubetree.grpc.tunnel.proto.TunnelMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.clientId_ = clientId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timestamp_ = timestamp_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.request_ = requestBuilder_ == null
            ? request_
            : requestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.response_ = responseBuilder_ == null
            ? response_
            : responseBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.correlationId_ = correlationId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof top.redjujubetree.grpc.tunnel.proto.TunnelMessage) {
        return mergeFrom((top.redjujubetree.grpc.tunnel.proto.TunnelMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(top.redjujubetree.grpc.tunnel.proto.TunnelMessage other) {
      if (other == top.redjujubetree.grpc.tunnel.proto.TunnelMessage.getDefaultInstance()) return this;
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasRequest()) {
        mergeRequest(other.getRequest());
      }
      if (other.hasResponse()) {
        mergeResponse(other.getResponse());
      }
      if (!other.getCorrelationId().isEmpty()) {
        correlationId_ = other.correlationId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              clientId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              correlationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object messageId_ = "";
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <pre>
     * 客户端ID
     * </pre>
     *
     * <code>string client_id = 2;</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 客户端ID
     * </pre>
     *
     * <code>string client_id = 2;</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 客户端ID
     * </pre>
     *
     * <code>string client_id = 2;</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端ID
     * </pre>
     *
     * <code>string client_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      clientId_ = getDefaultInstance().getClientId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端ID
     * </pre>
     *
     * <code>string client_id = 2;</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public top.redjujubetree.grpc.tunnel.proto.MessageType getType() {
      top.redjujubetree.grpc.tunnel.proto.MessageType result = top.redjujubetree.grpc.tunnel.proto.MessageType.forNumber(type_);
      return result == null ? top.redjujubetree.grpc.tunnel.proto.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(top.redjujubetree.grpc.tunnel.proto.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      type_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private top.redjujubetree.grpc.tunnel.proto.RequestPayload request_;
    private com.google.protobuf.SingleFieldBuilderV3<
        top.redjujubetree.grpc.tunnel.proto.RequestPayload, top.redjujubetree.grpc.tunnel.proto.RequestPayload.Builder, top.redjujubetree.grpc.tunnel.proto.RequestPayloadOrBuilder> requestBuilder_;
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     * @return The request.
     */
    public top.redjujubetree.grpc.tunnel.proto.RequestPayload getRequest() {
      if (requestBuilder_ == null) {
        return request_ == null ? top.redjujubetree.grpc.tunnel.proto.RequestPayload.getDefaultInstance() : request_;
      } else {
        return requestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     */
    public Builder setRequest(top.redjujubetree.grpc.tunnel.proto.RequestPayload value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
      } else {
        requestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     */
    public Builder setRequest(
        top.redjujubetree.grpc.tunnel.proto.RequestPayload.Builder builderForValue) {
      if (requestBuilder_ == null) {
        request_ = builderForValue.build();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     */
    public Builder mergeRequest(top.redjujubetree.grpc.tunnel.proto.RequestPayload value) {
      if (requestBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          request_ != null &&
          request_ != top.redjujubetree.grpc.tunnel.proto.RequestPayload.getDefaultInstance()) {
          getRequestBuilder().mergeFrom(value);
        } else {
          request_ = value;
        }
      } else {
        requestBuilder_.mergeFrom(value);
      }
      if (request_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     */
    public Builder clearRequest() {
      bitField0_ = (bitField0_ & ~0x00000010);
      request_ = null;
      if (requestBuilder_ != null) {
        requestBuilder_.dispose();
        requestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     */
    public top.redjujubetree.grpc.tunnel.proto.RequestPayload.Builder getRequestBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     */
    public top.redjujubetree.grpc.tunnel.proto.RequestPayloadOrBuilder getRequestOrBuilder() {
      if (requestBuilder_ != null) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        return request_ == null ?
            top.redjujubetree.grpc.tunnel.proto.RequestPayload.getDefaultInstance() : request_;
      }
    }
    /**
     * <pre>
     * 消息载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        top.redjujubetree.grpc.tunnel.proto.RequestPayload, top.redjujubetree.grpc.tunnel.proto.RequestPayload.Builder, top.redjujubetree.grpc.tunnel.proto.RequestPayloadOrBuilder> 
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            top.redjujubetree.grpc.tunnel.proto.RequestPayload, top.redjujubetree.grpc.tunnel.proto.RequestPayload.Builder, top.redjujubetree.grpc.tunnel.proto.RequestPayloadOrBuilder>(
                getRequest(),
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      return requestBuilder_;
    }

    private top.redjujubetree.grpc.tunnel.proto.ResponsePayload response_;
    private com.google.protobuf.SingleFieldBuilderV3<
        top.redjujubetree.grpc.tunnel.proto.ResponsePayload, top.redjujubetree.grpc.tunnel.proto.ResponsePayload.Builder, top.redjujubetree.grpc.tunnel.proto.ResponsePayloadOrBuilder> responseBuilder_;
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     * @return The response.
     */
    public top.redjujubetree.grpc.tunnel.proto.ResponsePayload getResponse() {
      if (responseBuilder_ == null) {
        return response_ == null ? top.redjujubetree.grpc.tunnel.proto.ResponsePayload.getDefaultInstance() : response_;
      } else {
        return responseBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     */
    public Builder setResponse(top.redjujubetree.grpc.tunnel.proto.ResponsePayload value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
      } else {
        responseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     */
    public Builder setResponse(
        top.redjujubetree.grpc.tunnel.proto.ResponsePayload.Builder builderForValue) {
      if (responseBuilder_ == null) {
        response_ = builderForValue.build();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     */
    public Builder mergeResponse(top.redjujubetree.grpc.tunnel.proto.ResponsePayload value) {
      if (responseBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          response_ != null &&
          response_ != top.redjujubetree.grpc.tunnel.proto.ResponsePayload.getDefaultInstance()) {
          getResponseBuilder().mergeFrom(value);
        } else {
          response_ = value;
        }
      } else {
        responseBuilder_.mergeFrom(value);
      }
      if (response_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     */
    public Builder clearResponse() {
      bitField0_ = (bitField0_ & ~0x00000020);
      response_ = null;
      if (responseBuilder_ != null) {
        responseBuilder_.dispose();
        responseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     */
    public top.redjujubetree.grpc.tunnel.proto.ResponsePayload.Builder getResponseBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     */
    public top.redjujubetree.grpc.tunnel.proto.ResponsePayloadOrBuilder getResponseOrBuilder() {
      if (responseBuilder_ != null) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        return response_ == null ?
            top.redjujubetree.grpc.tunnel.proto.ResponsePayload.getDefaultInstance() : response_;
      }
    }
    /**
     * <pre>
     * 响应载荷
     * </pre>
     *
     * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        top.redjujubetree.grpc.tunnel.proto.ResponsePayload, top.redjujubetree.grpc.tunnel.proto.ResponsePayload.Builder, top.redjujubetree.grpc.tunnel.proto.ResponsePayloadOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            top.redjujubetree.grpc.tunnel.proto.ResponsePayload, top.redjujubetree.grpc.tunnel.proto.ResponsePayload.Builder, top.redjujubetree.grpc.tunnel.proto.ResponsePayloadOrBuilder>(
                getResponse(),
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      return responseBuilder_;
    }

    private java.lang.Object correlationId_ = "";
    /**
     * <pre>
     * 关联ID，用于请求响应匹配
     * </pre>
     *
     * <code>string correlation_id = 7;</code>
     * @return The correlationId.
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 关联ID，用于请求响应匹配
     * </pre>
     *
     * <code>string correlation_id = 7;</code>
     * @return The bytes for correlationId.
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 关联ID，用于请求响应匹配
     * </pre>
     *
     * <code>string correlation_id = 7;</code>
     * @param value The correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关联ID，用于请求响应匹配
     * </pre>
     *
     * <code>string correlation_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationId() {
      correlationId_ = getDefaultInstance().getCorrelationId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关联ID，用于请求响应匹配
     * </pre>
     *
     * <code>string correlation_id = 7;</code>
     * @param value The bytes for correlationId to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:top.redjujubetree.tunnel.grpc.TunnelMessage)
  }

  // @@protoc_insertion_point(class_scope:top.redjujubetree.tunnel.grpc.TunnelMessage)
  private static final top.redjujubetree.grpc.tunnel.proto.TunnelMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new top.redjujubetree.grpc.tunnel.proto.TunnelMessage();
  }

  public static top.redjujubetree.grpc.tunnel.proto.TunnelMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TunnelMessage>
      PARSER = new com.google.protobuf.AbstractParser<TunnelMessage>() {
    @java.lang.Override
    public TunnelMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TunnelMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TunnelMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public top.redjujubetree.grpc.tunnel.proto.TunnelMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

