// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tunnel.proto

// Protobuf Java Version: 3.25.3
package top.redjujubetree.grpc.tunnel.proto;

public interface TunnelMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.redjujubetree.tunnel.grpc.TunnelMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string client_id = 2;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 2;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.top.redjujubetree.tunnel.grpc.MessageType type = 3;</code>
   * @return The type.
   */
  top.redjujubetree.grpc.tunnel.proto.MessageType getType();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
   * @return The request.
   */
  top.redjujubetree.grpc.tunnel.proto.RequestPayload getRequest();
  /**
   * <code>.top.redjujubetree.tunnel.grpc.RequestPayload request = 5;</code>
   */
  top.redjujubetree.grpc.tunnel.proto.RequestPayloadOrBuilder getRequestOrBuilder();

  /**
   * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
   * @return The response.
   */
  top.redjujubetree.grpc.tunnel.proto.ResponsePayload getResponse();
  /**
   * <code>.top.redjujubetree.tunnel.grpc.ResponsePayload response = 6;</code>
   */
  top.redjujubetree.grpc.tunnel.proto.ResponsePayloadOrBuilder getResponseOrBuilder();

  /**
   * <code>string correlation_id = 7;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlation_id = 7;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();
}
